# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 05:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLevelsDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=40)),
                ('level1', models.TextField()),
                ('level2', models.TextField()),
                ('level3', models.TextField()),
                ('level4', models.TextField()),
                ('level5', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Submitted'), (3, 'Edited')], default=1)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('behavior', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('on_time', models.BooleanField(default=True)),
                ('electronics', models.BooleanField(default=True)),
                ('personal_goals', models.BooleanField(default=True)),
                ('leaving_class', models.BooleanField(default=True)),
                ('teacher_comments', models.TextField()),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('student_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
