# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_behaviorlevelsdefinition_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progresses'},
        ),
    ]
